# Generated by Django 5.0.1 on 2024-02-05 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='father_phone',
            new_name='father_phone_number',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='mother_phone',
            new_name='mother_phone_number',
        ),
    ]
