# Generated by Django 5.0.1 on 2024-03-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='img_name',
            field=models.CharField(null=True),
        ),
    ]
