# Generated by Django 5.0.1 on 2024-02-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0002_rename_father_phone_student_father_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='national_ID',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
